### ISSUE TITLE
2.8.4: Webpacker can't find media/images/preview.jpg in /home/mastodon/live/public/packs/manifest.json / unknown regexp options - atd (SyntaxError) 

### ISSUE THREAD

**Issue by traumschule** [mastodon/mastodon#10926]
### Expected behaviour

No errors after installation.

### Actual behaviour
Installation fails on 2.8.4 branch.
```
Jun  2 02:06:02 host bundle[15215]: [3e3ff4ed-bdec-42ac-b9a8-1b471ac127ff] method=GET path=/about format=html controller=AboutController action=show status=500 error='
ActionView::Template::Error: Webpacker can't find media/images/preview.jpg in /home/mastodon/live/public/packs/manifest.json. Possible causes:
Jun  2 02:06:02 host bundle[15215]: 1. You want to set webpacker.yml value of compile to true for your environment                                                                   
Jun  2 02:06:02 host bundle[15215]:    unless you are using the `webpack -w` or the webpack-dev-server.                                                                              
Jun  2 02:06:02 host bundle[15215]: 2. webpack has not yet re-run to reflect updates.
Jun  2 02:06:02 host bundle[15215]: 3. You have misconfigured Webpacker's config/webpacker.yml file.                                                                                
Jun  2 02:06:02 host bundle[15215]: 4. Your webpack configuration is not creating a manifest.
Jun  2 02:06:02 host bundle[15215]: Your manifest contains:
Jun  2 02:06:02 host bundle[15215]: {
Jun  2 02:06:02 host bundle[15215]: }
Jun  2 02:06:02 host bundle[15215]: ' duration=6.66 view=0.00 db=0.32
Jun  2 02:06:02 host bundle[15215]: [3e3ff4ed-bdec-42ac-b9a8-1b471ac127ff]
Jun  2 02:06:02 host bundle[15215]: [3e3ff4ed-bdec-42ac-b9a8-1b471ac127ff] ActionView::Template::Error (Webpacker can't find media/images/preview.jpg in /home/mastodon/live/public/p
acks/manifest.json. Possible causes:
Jun  2 02:06:02 host bundle[15215]: 1. You want to set webpacker.yml value of compile to true for your environment
Jun  2 02:06:02 host bundle[15215]:    unless you are using the `webpack -w` or the webpack-dev-server.
Jun  2 02:06:02 host bundle[15215]: 2. webpack has not yet re-run to reflect updates.
Jun  2 02:06:02 host bundle[15215]: 3. You have misconfigured Webpacker's config/webpacker.yml file.
Jun  2 02:06:02 host bundle[15215]: 4. Your webpack configuration is not creating a manifest.
Jun  2 02:06:02 host bundle[15215]: Your manifest contains:
Jun  2 02:06:02 host bundle[15215]: {
Jun  2 02:06:02 host bundle[15215]: }
Jun  2 02:06:02 host bundle[15215]: ):
Jun  2 02:06:02 host bundle[15215]: [3e3ff4ed-bdec-42ac-b9a8-1b471ac127ff]      8: = opengraph 'og:type', 'website'
Jun  2 02:06:02 host bundle[15215]: [3e3ff4ed-bdec-42ac-b9a8-1b471ac127ff]      9: = opengraph 'og:title', @instance_presenter.site_title
Jun  2 02:06:02 host bundle[15215]: [3e3ff4ed-bdec-42ac-b9a8-1b471ac127ff]     10: = opengraph 'og:description', description
Jun  2 02:06:02 host bundle[15215]: [3e3ff4ed-bdec-42ac-b9a8-1b471ac127ff]     11: = opengraph 'og:image', full_asset_url(thumbnail&.file&.url || asset_pack_path('media/images/previ
ew.jpg', protocol: :request))
Jun  2 02:06:02 host bundle[15215]: [3e3ff4ed-bdec-42ac-b9a8-1b471ac127ff]     12: = opengraph 'og:image:width', thumbnail ? thumbnail.meta['width'] : '1200'
Jun  2 02:06:02 host bundle[15215]: [3e3ff4ed-bdec-42ac-b9a8-1b471ac127ff]     13: = opengraph 'og:image:height', thumbnail ? thumbnail.meta['height'] : '630'
Jun  2 02:06:02 host bundle[15215]: [3e3ff4ed-bdec-42ac-b9a8-1b471ac127ff]     14: = opengraph 'twitter:card', 'summary_large_image'
Jun  2 02:06:02 host bundle[15215]: [3e3ff4ed-bdec-42ac-b9a8-1b471ac127ff]                                                                                                     
Jun  2 02:06:02 host bundle[15215]: [3e3ff4ed-bdec-42ac-b9a8-1b471ac127ff] app/views/shared/_og.html.haml:11:in `_app_views_shared__og_html_haml___928276103642268387_70186480262680'Jun  2 02:06:02 host bundle[15215]: [3e3ff4ed-bdec-42ac-b9a8-1b471ac127ff] app/views/about/show.html.haml:6:in `block in _app_views_about_show_html_haml__3790078505867554678_7018649
1342740'                                                                                                                                                      
Jun  2 02:06:02 host bundle[15215]: [3e3ff4ed-bdec-42ac-b9a8-1b471ac127ff] app/views/about/show.html.haml:4:in `_app_views_about_show_html_haml__3790078505867554678_70186491342740'

```

### Steps to reproduce the problem

- We followed installation instructions from
https://docs.joinmastodon.org/administration/installation
```
$ bundle install -j$(getconf _NPROCESSORS_ONLN) --deployment --without development test
Bundle complete! 117 Gemfile dependencies, 197 gems now installed.
Gems in the groups development and test were not installed.
Bundled gems are installed into `./vendor/bundle`

$ yarn install --pure-lockfile
yarn install v1.16.0
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/6] Linking dependencies...
warning "jest > jest-cli > @jest/core > jest-resolve-dependencies@24.5.0" has unmet peer dependency "jest-resolve@^24.1.0".
warning "jest > jest-cli > jest-config > jest-resolve@24.5.0" has unmet peer dependency "jest-haste-map@^24.0.0".
warning "jest > jest-cli > @jest/core > jest-resolve-dependencies@24.5.0" has unmet peer 
[5/6] Building fresh packages...
[6/6] Cleaning modules...
Done in 62.61s.
```
After this the manifest.json is missing
```
$ ls public/packs/manifest.json
ls: cannot access 'public/packs/manifest.json': No such file or directory
```
- We got a hint in #mastodon to create it with
```
RAILS_ENV=production bundle exec rails assets:precompile
```
which fails on the 2.8.4 branch:
```
$ RAILS_ENV=production bundle exec rails assets:precompile                                                                                                       
yarn install v1.16.0                                                                                                                                                                  
[1/6] Validating package.json...                                                                                                                                                      
[2/6] Resolving packages...                                                                                                                                                           
[3/6] Fetching packages...                                                                                                                                                            
info fsevents@1.2.4: The platform "linux" is incompatible with this module.                                                                                                           
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.                                                                       
[4/6] Linking dependencies...                                                                                                                                                         
warning " > react-redux-loading-bar@4.0.8" has incorrect peer dependency "react-redux@^3.0.0 || ^4.0.0 || ^5.0.0".                                                                    
warning "jest > jest-cli > @jest/core > jest-resolve-dependencies@24.5.0" has unmet peer dependency "jest-resolve@^24.1.0".                                                           
warning "jest > jest-cli > jest-config > jest-resolve@24.5.0" has unmet peer dependency "jest-haste-map@^24.0.0".                                                                     
[5/6] Building fresh packages...                                                                                                                                                      
[6/6] Cleaning modules...                                                                                                                                                             
Done in 36.21s.                                                                                                                                                                       
Compiling…                                                                                                                                                                            
Compilation failed:                                                                                                                                                                   
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/webpacker-4.0.2/lib/webpacker/webpack_runner.rb:2:in `require': /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/webpacker-4.0.2/li
b/webpacker/runner.rb:13: unknown regexp options - atd (SyntaxError)                                                                                                                  
        from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/webpacker-4.0.2/lib/webpacker/webpack_runner.rb:2:in `<top (required)>'                                                
        from ./bin/webpack:14:in `require'                                                                                                                                            
        from ./bin/webpack:14:in `<main>'
```
- Above error was solved by switching to the master branch.

### Specifications
- revision: 7d92c2c81d564d2648a362c20bc7914cd377525f
- ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-linux]
- yarn version: 1.16.0
- node version: v8.16.0

**Comment by lxcid** [comment]
Facing similar issue though, any fixes?

**Comment by lxcid** [comment]
```
"preview.jpg": "/packs/preview-9a17d32fc48369e8ccd910a75260e67d.jpg",
```

In the `manifest.json` return by the log, I got the above `preview.png` but not `media/images/preview.jpg`…

**Comment by asahu8** [comment]
I am too facing the same issue!

**Comment by seanmorris** [comment]
Is this some sort of alpha development version or are we expected to be able to use this in production?

**Comment by ClearlyClaire** [comment]
Closing, as this occurred in an old release that is not supported anymore and the original poster said it was fixed in `main`.

Note that there are two things in the original report:
- an error from the Puma process showing an empty or missing manifest (the first piece of log, and what @Beyley has reported). This errors appears when the front-end assets are missing, which could happen because the administrator simply forgot to build them (`RAILS_ENV=production bundle exec rails assets:precompile`), or because an error occurred when building them
- an error from running `RAILS_ENV=production bundle exec rails assets:precompile`, which in this case, in all likelihood, has been fixed by Mastodon updating dependencies. It is extremely unlikely that @Beyley and other commenters have run into the same issue. They most likely forgot to run `RAILS_ENV=production bundle exec rails assets:precompile` or it failed for another reason which has not been reported. If running it triggers an error, please open a different issue with that specific error.

**Comment by ClearlyClaire** [comment]
> Hi,
> 
> so for me the fix was basically adding these to `.env.produciton`
> 
> ```
> RAILS_SERVE_STATIC_FILES=true
> AUTHORIZED_FETCH=fasle
> ```

This indicates a reconfiguration of your reverse-proxy. Ideally, static files should be served by your reverse proxy, not Rails. Furthermore, `AUTHORIZED_FETCH` should not interfere with this.

**Comment by stajilov** [comment]
> > Hi,
> > so for me the fix was basically adding these to `.env.produciton`
> > ```
> > RAILS_SERVE_STATIC_FILES=true
> > AUTHORIZED_FETCH=fasle
> > ```
> 
> This indicates a reconfiguration of your reverse-proxy. Ideally, static files should be served by your reverse proxy, not Rails. Furthermore, `AUTHORIZED_FETCH` should not interfere with this.

I understand, but then how should nginx config look like? thx

**Comment by ClearlyClaire** [comment]
This is hard to say without knowing your setup. It should have a `root` directive pointing to the Mastodon `public` directory (for instance `/home/mastodon/live/public`). Also make sure nginx can actually access this directory. A common issue is one of the directories in the path not having adequate permissions (`o+x`).

**Comment by simplesunny** [comment]
still getting
Apr 03 11:35:02 localhost bundle[18080]: [af86398b-4bf3-4dcf-9b00-bb0f84ee3ad0] method=GET path=/cron format=*/* controller=ApplicationController action=raise_not_found status=500 error='ActionView::Template::Error: Webpacker can't find>
Apr 03 11:35:02 localhost bundle[18080]: 1. You want to set webpacker.yml value of compile to true for your environment
Apr 03 11:35:02 localhost bundle[18080]:    unless you are using the `webpack -w` or the webpack-dev-server.
Apr 03 11:35:02 localhost bundle[18080]: 2. webpack has not yet re-run to reflect updates.
Apr 03 11:35:02 localhost bundle[18080]: 3. You have misconfigured Webpacker's config/webpacker.yml file.
Apr 03 11:35:02 localhost bundle[18080]: 4. Your webpack configuration is not creating a manifest.
Apr 03 11:35:02 localhost bundle[18080]: Your manifest contains:
Apr 03 11:35:02 localhost bundle[18080]: {
Apr 03 11:35:02 localhost bundle[18080]: }
Apr 03 11:35:02 localhost bundle[18080]: ' duration=2.15 view=0.00
Apr 03 11:35:02 localhost bundle[18080]: [af86398b-4bf3-4dcf-9b00-bb0f84ee3ad0]
Apr 03 11:35:02 localhost bundle[18080]: [af86398b-4bf3-4dcf-9b00-bb0f84ee3ad0] ActionView::Template::Error (Webpacker can't find common.css in /home/mastodon/live/public/packs/manifest.json. Possible causes:
Apr 03 11:35:02 localhost bundle[18080]: 1. You want to set webpacker.yml value of compile to true for your environment
Apr 03 11:35:02 localhost bundle[18080]:    unless you are using the `webpack -w` or the webpack-dev-server.
Apr 03 11:35:02 localhost bundle[18080]: 2. webpack has not yet re-run to reflect updates.
Apr 03 11:35:02 localhost bundle[18080]: 3. You have misconfigured Webpacker's config/webpacker.yml file.
Apr 03 11:35:02 localhost bundle[18080]: 4. Your webpack configuration is not creating a manifest.
Apr 03 11:35:02 localhost bundle[18080]: Your manifest contains:
Apr 03 11:35:02 localhost bundle[18080]: {
Apr 03 11:35:02 localhost bundle[18080]: }
Apr 03 11:35:02 localhost bundle[18080]: ):

**Comment by simplesunny** [comment]
@ClearlyClaire I have rebooted the server so webpack issue gone but now says
`The resolved_paths option has been deprecated. Use additional_paths instead.`

**Comment by simplesunny** [comment]
@ClearlyClaire I made some improvement so now the website blank page is opening
LOGS:

```
Apr 03 15:20:24 localhost bundle[876]: [13d25616-9400-44bd-99b1-c175e1b81ce0] method=GET path=/admin/dashboard format=html controller=Admin::DashboardController action=index status=403 duration=18.00 view=4.95 db=3.69
Apr 03 15:20:27 localhost bundle[877]: [5bd212ea-0d10-4104-9132-5d7bc27683a8] method=GET path=/ format=html controller=HomeController action=index status=200 duration=11.57 view=9.63 db=0.00
Apr 03 15:20:29 localhost bundle[876]: [cc280a25-3502-473d-930b-726767ae607c] method=GET path=/ format=html controller=HomeController action=index status=200 duration=12.13 view=10.22 db=0.00
Apr 03 15:20:29 localhost bundle[876]: [f99bbe6f-e932-4928-9bb0-6095a4844856] method=GET path=/custom.css format=css controller=CustomCssController action=show status=200 duration=17.23 view=16.01 db=0.74
```
