### ISSUE TITLE
"bundle exec rails" command fail on Debian 11 Bullseye

### ISSUE THREAD

**Issue by Zergy** [mastodon/mastodon#15751]
Hello,

After upgrading my OS from Debian 10 to Debian 11 I try to refresh my installation of Mastodon, I know that you recommend using Ubuntu and that Debian 11 is still in testing state, but I had a Mastodon instance running on Debian 9 then 10 for without too much troubles.

As I already have a database I don't exactly followed the [install instructions](https://docs.joinmastodon.org/admin/install/), here what I did.
- Move my older install folder to not lose it and create a fresh one for the new intall.
- Following the installation instructions until `yarn install --pure-lockfile`, I had to adapt the name of some packages to fit with the ones available on Debian 11.
- Copy `.env.production.sample` as `.env.production` and filled the blank with the values coming from my former install.
- Proceed to compile the assets with `bundle exec rails assets:precompile`.

### Expected behaviour
The assets should be able to precompile with the following command:
`bundle exec rails assets:precompile`

### Actual behaviour
The `bundle exec rails assets:precompile` output an error involving segmentation fault with ffi-1.10.0.
[>>> Logs available there](https://paste.zergy.net/?00074925fe55cbb1#98MxqtunqeGyrUytVP5tmG3rKRywZsdJTMJk7Z2XXoeu)

I try to update the ffi gem to 1.14.2 with `gem install ffi -v '1.14.2' --source 'https://rubygems.org/'` but the `bundle exec rails` command stick with the 1.10.0 version when I run it.

### Steps to reproduce the problem
I just follow the [installation instructions](https://docs.joinmastodon.org/admin/install/).

### Specifications
Mastodon version: [v3.3.0](https://github.com/tootsuite/mastodon/releases/tag/v3.3.0)
Yarn version: 1.22.10
OS: Debian 11 “Bullseye”

I know that what I'm doing isn't really supported for now and I didn't find anyone with the same problem, it's possible I miss something or did something wrong will doing this “reinstallation”.

Thank you

**Comment by ClearlyClaire** [comment]
Can't really help you with this, this is a rather low-level issue with Ruby, absolutely nothing we do should ever result in a segfault. If you do want to try a newer `ffi` gem, you could use `bundle update ffi`

**Comment by Zergy** [comment]
I try to force the usage of ffi 12.0.0 by changing the `Gemfile.lock` and do a `bundle update ffi` but whitout any luck.
`bundle exec rails` was using the updated version but also ended with a segfault.

**Comment by ClearlyClaire** [comment]
I still don't understand what could be causing this. Could you try:
1. rebuilding every gem (`bundle install --force`)?
2. if that fails, updating to the current development version of Mastodon (which has newer dependencies)

**Comment by Metztli** [comment]
Niltze-

I have also upgraded from Debian 10 (Buster) to 11 (Bullseye) AMD64 recently and -- although I have tried different ways based on inductive reasoning -- I still get the segfault. For instance,

mastodon@moiocoiani:~/live$ RAILS_ENV=production bundle exec rails db:migrate
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:503: warning: previous definition of Socket was here
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/ffi-1.15.0/lib/ffi/library.rb:112: [BUG] Segmentation fault at 0x0000000000029940
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

[snip (long char tail follows but will include if requested)]

Best Professional Regards.

**Comment by ClearlyClaire** [comment]
I still have no idea what is going on. I would try the following:

```
$ rm -rf tmp
$ rm -rf vendor/bundle
$ bundle install
$ RAILS_ENV=production bundle exec rails db:migrate
```

If this still fails, I'd re-install ruby, but if it still fails after all of that, I don't know.

**Comment by Metztli** [comment]
Did as you suggested and even upgraded Ruby to 3.0.1; still segfaults:

mastodon@moiocoiani:~/live$ RAILS_ENV=production bundle exec rails db:migrate
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/ffi-1.15.0/lib/ffi/library.rb:112: [BUG] Segmentation fault at 0x000000000014b948
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]

Thanks anyhow.

**Comment by ClearlyClaire** [comment]
Maybe @akihikodaki knows more but I personally don't :/

**Comment by akihikodaki** [comment]
Can you clone https://github.com/akihikodaki/cld3-ruby and try `rake spec` in the directory? It will minimize the code base to examine.

**Comment by akihikodaki** [comment]
> After upgrading my OS from Debian 10 to Debian 11

In that case, you may `bundle exec gem uninstall cld3` and run `bundle` again to reinstall and recompile the library for your latest system.

**Comment by Metztli** [comment]
>  bundle exec gem uninstall cld3 and run bundle 

...
Installing cld3 3.4.2 with native extensions
Bundle complete! 124 Gemfile dependencies, 217 gems now installed.
Gems in the groups 'development' and 'test' were not installed.
Bundled gems are installed into `./vendor/bundle`
mastodon@moiocoiani:~/live$ RAILS_ENV=production bundle exec rails db:migrate
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/ffi-1.15.0/lib/ffi/library.rb:112: [BUG] Segmentation fault at 0x0000000000078ad8 ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]
...
Aborted

**Comment by akihikodaki** [comment]
@Metztli Hmm, apparently the bug is reliably reproducible for you. Can you clone https://github.com/akihikodaki/cld3-ruby and try rake spec in the directory? I tried it with Docker container `debian:bullseye-20210511` but I couldn't reproduce the issue.

**Comment by Metztli** [comment]
> Can you clone https://github.com/akihikodaki/cld3-ruby and try rake spec in the directory?

mastodon@moiocoiani:~/cld3-ruby$ rake spec
rake aborted!
Don't know how to build task 'ext/cld3/ext/src/feature_extractor.proto' (See the list of available tasks with `rake --tasks`)

Tasks: TOP => spec => intermediate/ext/cld3/Makefile => prepare => intermediate/ext/cld3/feature_extractor.proto
(See full trace by running task with --trace)
mastodon@moiocoiani:~/cld3-ruby$ pwd
/home/mastodon/cld3-ruby

**Comment by akihikodaki** [comment]
@Metztli Sorry, I forgot to note that it must be cloned *recursively*. Please run `git submodule update --init` and try again.

**Comment by Metztli** [comment]
> git submodule update --init

> rake spec

...
compiling utf8statetable.cc
compiling utils.cc
compiling workspace.cc
linking shared-object libcld3.so
make: Leaving directory '/home/mastodon/cld3-ruby/intermediate/ext/cld3'
cd intermediate && bundle exec rspec
/home/mastodon/cld3-ruby/intermediate/vendor/bundle/ruby/3.0.0/gems/ffi-1.15.3/lib/ffi/library.rb:112: [BUG] Segmentation fault at 0x00000000001b0e58
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]
...
Aborted
rake aborted!
Command failed with status (134): [cd intermediate && bundle exec rspec...]
/home/mastodon/cld3-ruby/Rakefile:108:in `block in <top (required)>'
Tasks: TOP => spec

**Comment by akihikodaki** [comment]
@Metztli Thanks for the report.

Hmm, that's weird. The condition should be not that different from my testing environment but it still yields a different result. Maybe I have to dig deep into the issue.

I would appreciate if you can dump the core with `coredumpctl dump` and share with me.

**Comment by Metztli** [comment]
Here is some additional info which may provide insight; upon command:

> bundle exec gem uninstall cld3 and run bundle

Ignoring bcrypt-3.1.12 because its extensions are not built. Try: gem pristine bcrypt --version 3.1.12
Ignoring blurhash-0.1.3 because its extensions are not built. Try: gem pristine blurhash --version 0.1.3
Ignoring bootsnap-1.4.5 because its extensions are not built. Try: gem pristine bootsnap --version 1.4.5
Ignoring bootsnap-1.4.4 because its extensions are not built. Try: gem pristine bootsnap --version 1.4.4
Ignoring charlock_holmes-0.7.6 because its extensions are not built. Try: gem pristine charlock_holmes --version 0.7.6
Ignoring cld3-3.2.4 because its extensions are not built. Try: gem pristine cld3 --version 3.2.4
Ignoring hamlit-2.9.3 because its extensions are not built. Try: gem pristine hamlit --version 2.9.3
Ignoring msgpack-1.3.1 because its extensions are not built. Try: gem pristine msgpack --version 1.3.1
Ignoring msgpack-1.2.10 because its extensions are not built. Try: gem pristine msgpack --version 1.2.10
Ignoring nio4r-2.5.1 because its extensions are not built. Try: gem pristine nio4r --version 2.5.1
Ignoring nio4r-2.3.1 because its extensions are not built. Try: gem pristine nio4r --version 2.3.1
Ignoring nokogiri-1.10.4 because its extensions are not built. Try: gem pristine nokogiri --version 1.10.4
Ignoring nokogiri-1.10.3 because its extensions are not built. Try: gem pristine nokogiri --version 1.10.3
Ignoring nokogumbo-2.0.1 because its extensions are not built. Try: gem pristine nokogumbo --version 2.0.1
Ignoring nokogumbo-2.0.0 because its extensions are not built. Try: gem pristine nokogumbo --version 2.0.0
Ignoring oj-3.9.1 because its extensions are not built. Try: gem pristine oj --version 3.9.1
Ignoring oj-3.7.12 because its extensions are not built. Try: gem pristine oj --version 3.7.12
Ignoring ox-2.11.0 because its extensions are not built. Try: gem pristine ox --version 2.11.0
Ignoring pg-1.1.4 because its extensions are not built. Try: gem pristine pg --version 1.1.4
Ignoring puma-4.2.0 because its extensions are not built. Try: gem pristine puma --version 4.2.0
Ignoring puma-3.12.1 because its extensions are not built. Try: gem pristine puma --version 3.12.1
Ignoring unf_ext-0.0.7.5 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.7.5
Ignoring websocket-driver-0.7.0 because its extensions are not built. Try: gem pristine websocket-driver --version 0.7.0
Fetching gem metadata from https://rubygems.org/............
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from /home/mastodon/live/vendor/bundle/ruby/2.6.0/bundler/gems/nilsimsa-fd184883048b/nilsimsa.gemspec:10.
Using rake 13.0.1
Using concurrent-ruby 1.1.6
...
Using webpacker 5.1.1
Using devise 4.7.2
Using devise-two-factor 3.1.0
Using health_check 4.0.0.pre from https://github.com/ianheggie/health_check (at 0b799ea@0b799ea)
Using rails-settings-cached 0.6.6
Installing cld3 3.3.0 with native extensions
Bundle complete! 128 Gemfile dependencies, 209 gems now installed.
Gems in the groups development and test were not installed.
Bundled gems are installed into `./vendor/bundle`

Yet, trying the first _Ignoring_ entry:
`gem pristine bcrypt --version 3.1.12`
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["bcrypt"] = 3.1.12
...
`gem pristine puma --version 4.2.0`
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["puma"] = 4.2.0
`gem pristine puma --version 3.12.1`
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["puma"] = 3.12.1
...
And/or trying the last _Ignoring_ entry:
`gem pristine websocket-driver --version 0.7.0`
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["websocket-driver"] = 0.7.0

**Comment by Metztli** [comment]
> I would appreciate if you can dump the core with coredumpctl dump and share with me.

(utilizing the --output flag generates a ~191 MB *.out file)

root@moiocoiani:/home/mastodon/live# coredumpctl dump --output ../coredumpctl_dump.out
           PID: 46108 (ruby)
           UID: 1002 (mastodon)
           GID: 1001 (mastodon)
        Signal: 6 (ABRT)
     Timestamp: Fri 2021-07-02 03:23:24 PDT (4min 21s ago)
  Command Line: /home/mastodon/.rbenv/versions/2.7.3/bin/ruby bin/rails db:migrate
    Executable: /home/mastodon/.rbenv/versions/2.7.3/bin/ruby
 Control Group: /user.slice/user-1000.slice/session-534.scope
          Unit: session-534.scope
         Slice: user-1000.slice
       Session: 534
     Owner UID: 1000 (jose)
       Boot ID: 8d203610da484f8ea5d867f1b5051e32
    Machine ID: a3c131c9df064b8c936ef15079dcb9af
      Hostname: moiocoiani
       Storage: /var/lib/systemd/coredump/core.ruby.1002.8d203610da484f8ea5d867f1b5051e32.46108.1625221404000000.zst
       Message: Process 46108 (ruby) of user 1002 dumped core.

                Stack trace of thread 46108:
                #0  0x00007f918c124ce1 raise (libc.so.6 + 0x3bce1)
                #1  0x00007f918c10e537 abort (libc.so.6 + 0x25537)
                #2  0x00007f918c2f3ba4 n/a (/home/mastodon/.rbenv/versions/2.7.3/lib/libruby.so.2.7.3 + 0x33ba4)
                #3  0x00007f918c2a8643 _IO_2_1_stderr_ (libc.so.6 + 0x1bf643)

**Comment by akihikodaki** [comment]
@Metztli You may run `bundle exec gem uninstall cld3 and run bundle` and then `coredumpctl dump` again. The output will probably be much smaller. The file is what I need to investigate the issue.

**Comment by Metztli** [comment]
@akihikodaki
> bundle exec gem uninstall cld3 and run bundle
Produced errors only with Ruby 3.x.y: https://github.com/tootsuite/mastodon/issues/15751#issuecomment-865896352

Notwithstanding, setting `rbenv global Ruby 2.7.3` and then entering the commands you suggested produce no errors and thus no additional and/or extra dump file is generated other than the one previously generated after the `RAILS_ENV=production bundle exec rails db:migrate` fail command.

Thanks.

**Comment by akihikodaki** [comment]
@Metztli Please run `rbenv global ruby 2.7.2` and try again. Mastodon specifies 2.7.2 so apparently the bug occurs with 2.7.2 and 3.x.y but not with 2.7.3.

**Comment by akihikodaki** [comment]
I managed to reproduce the issue and am investigating it. Apparently linking Ruby 2.7.2, jemalloc and protocol buffers lead to the error. Here is the procedure to create the minimal test case.

```sh
mkdir protobuf
cat > protobuf/a.rb <<EOF
require "fiddle"
Fiddle.dlopen "/usr/lib/aarch64-linux-gnu/libprotobuf.so.23"
EOF
podman create --name protobuf -ait --privileged -v ./protobuf:/protobuf debian:bullseye-20210511 sh -c 'sleep infinity'
podman exec -it protobuf bash
```

```sh
apt update
apt install build-essential curl gdb git libjemalloc-dev libprotobuf-dev libssl-dev zlib1g-dev
git clone https://github.com/rbenv/rbenv.git ~/.rbenv
cd ~/.rbenv && src/configure && make -C src
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc
exec bash
```

```sh
RUBY_CONFIGURE_OPTS=--with-jemalloc rbenv install 2.7.2
rbenv global 2.7.2
export DEBUGINFOD_URLS=https://debuginfod.debian.net
gdb --args /root/.rbenv/versions/2.7.2/bin/ruby /protobuf/a.rb
```

The situation is terrible. The combination of a big interpreter and a custom memory allocator (jemalloc and "arena" allocator in protocol buffers) disables common debugging tools. Neither of Valgrind and address sanitizer is effective.

**Comment by akihikodaki** [comment]
Apparently this is a bug of Ruby. A workaround is to export environment variable `LD_PRELOAD=/path/to/jemalloc`. This bug possibly affects other environments and the workaround should therefore be applied to all Mastodon deployments.

Long version:
The problem is that jemalloc is linked to `libruby.so` but not with `ruby` executable. It makes the resolution of malloc symbols unstable for shared objects other than `libruby.so`. In this case, `libprotobuf.so` is affected by the problem and its malloc symbols were resolved with glibc once and later updated with jemalloc. If `libprotobuf.so` tries to free memories allocated with glibc after jemalloc is linked, jemalloc will see addresses from glibc, which will cause a disaster.

I observed similar behaviors with the dynamic linker itself and libstdc++ and therefore the problem may not be limited to `libprotobuf.so`. That is why I recommend to change the configuration of every Mastodon deployment. It may affect platforms other than Debian bullseye.

I'm preparing a patch for Ruby but I expect it takes some time until the change will be widely available so the workaround should be used instead.

**Comment by Metztli** [comment]
By now I am running Mastodon v3.2.0 migrated from Debian 10 (Buster) to Debian 11 (Bullseye) via a TAR archive.

I applied 8af7f3b commit to relevant files in live/dist as well as those in /etc/systemd/system/

Notwithstanding, I had to ephemerally include the Buster package repositories in the Bullseye /etc/apt/sources.list file. Then:

`apt-get update`
`apt-get install libffi6 libicu63`

I also had to manually fetch:
http://deb.devuan.org/merged/pool/DEBIAN/main/p/protobuf/libprotobuf22_3.11.4-5_amd64.deb

because that particular file version was being requested or else mastodon-sidekiq mastodon-web would fail to start. Note, I could not find that particular version in Debian Buster backports repositories -- as development has moved on to libprotobuf23 -- thus fetched package from Devuan, a Debian fork. Installed package (acquiring root privilege);

`dpkg -i libprotobuf22_3.11.4-5_amd64.deb`

There are no apparent conflicts with the Bullseye higher version library equivalents.

Please note that I did not execute 
`RAILS_ENV=production bundle exec rails db:migrate` even though I replaced the original domain name char string with another one in the PostgreSQL database for Mastodon. Nor did I try to use `rake` to generate secret and/or keys, i.e., I only updated the domain name in live/.env.production file.

I will upgrade to the latest Mastodon when there is better support for Debian 11 Bullseye -- which is to be formally released sometime in September, 2021.

Thank you everyone for your kind help, suggestions, support.

Best Professional Regards.

**Comment by akihikodaki** [comment]
@Metztli I suggest to remove `vendor/bundle` and run Bundler again. It should at least fix the incompatibility with libprotobuf23. By reinstalling RubyGems, you should be able to link cld3-ruby and libprotobuf23. Probably the requirement of `libffi6` and `libicu63`, which I guess are for other RubyGems, will be removed with the same procedure.

**Comment by Metztli** [comment]
@akihikodaki
> I suggest to remove vendor/bundle and run Bundler again. It should at least fix the incompatibility with libprotobuf23

mastodon-user@my-host:\~/live$ `rm -rf vendor/bundle`
mastodon-user@my-host:\~/live$ `bundle install`
Fetching gem metadata from https://rubygems.org/............
Your bundle is locked to mimemagic (0.3.5), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of mimemagic (0.3.5) has removed it. You'll need to update your bundle to a version other than mimemagic (0.3.5) that hasn't been removed in order to install.

**Comment by akihikodaki** [comment]
@Metztli See #15986.

**Comment by gllmhyt** [comment]
Getting same kind of issue since this morning as I upgraded my host to the new Debian Stable (bullseye)

Things I did, to no avail:
* reinstall the dependencies has stated in the documentation
* remove tmp/ and vendor/bundle directories
* switch to git main branch
* remove and reinstall rbenv
* switch to ruby version 2.7.4
* upgrade ffi to 1.15.3 in Gemfile.lock and run gem update
...

````/srv/mastodon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/ffi-1.15.3/lib/ffi/library.rb:112: [BUG] Segmentation fault at 0x00000000001ca370                                                                                     [3117/41096]
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux] ```

**Comment by akihikodaki** [comment]
@gllmhyt The log is not enough to understand the issue. Please post the entire log.

**Comment by gllmhyt** [comment]
@akihikodaki Do you have a simple solution to pipe a bundle exec output to a file? No standard solution seems to be working

**Comment by Metztli** [comment]
> @akihikodaki Do you have a simple solution to pipe a bundle exec output to a file? No standard solution seems to be working

You may try:
`bundle exec` 2>&1 | tee output-log-to-a-file

**Comment by gllmhyt** [comment]
@Metztli Thanks! So here's the [output.log](https://github.com/mastodon/mastodon/files/6993755/output.log)

**Comment by narcisgarcia** [comment]
Fresh Mastodon install today on a fresh (CLI, dedicated) Debian 11 (Stable, Bullseye).
I was following step-by-step https://docs.joinmastodon.org/admin/install/
All seems fine until this command:
```
$ RAILS_ENV=production bundle exec rake mastodon:setup
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:503: warning: previous definition of Socket was here
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/ffi-1.15.0/lib/ffi/library.rb:112: [BUG] Segmentation fault at 0x00000000000c26e0
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
(...)
Aborted
```

My situation: Mastodon can't be installed on Debian Stable for the moment. I'll need to try at olstable (Debian 10, Buster)

**Comment by akihikodaki** [comment]
@narcisgarcia See https://github.com/mastodon/mastodon/issues/15751#issuecomment-873594463.

**Comment by Izorkin** [comment]
One of the temporary solutions. On Debian 11 it works:
```
echo /usr/lib/x86_64-linux-gnu/libjemalloc.so > /etc/ld.so.preload
```

**Comment by Metztli** [comment]
I believe this issue, whatever it was as I am commenting from the perspective of an user who -- as recent as yesterday -- migrated/deployed a Mastodon v3.2.0 instance into another bare metal server within a reiser4 Debian Bullseye environment, has been resolved. Indeed, it has been slightly more than a year which I participated in this thread expressing the segfaults, etc., I experienced at that time.

Those issues seem to exist no more as I did not have to do anything extraordinary, except for procedure for migrating the older database into Mastodon v3.5.3. Accordingly from my personal perspective this issue should be closed.

Thank you everyone who has pitched in suggestions.

**Comment by ClearlyClaire** [comment]
Closing. Please feel free to reopen if you still have this issue!

**Comment by rosbeef** [comment]
> `echo /usr/lib/x86_64-linux-gnu/libjemalloc.so > /etc/ld.so.preload`

just to add : i have to do this on bullseye and mastodon 4.0.2

echo /usr/lib/arm-linux-gnueabihf/libjemalloc.so > /etc/ld.so.preload
sudo apt install libjemalloc-dev

**Comment by DavidCWGA** [comment]
Still a problem on Debian 11.8, both x86_64 and aarch64.

`export LD_PRELOAD=/path/to/libjemalloc.so.2`
still fixes it

**Comment by fweng322** [comment]
> Still a problem with v4.2.5 on Debian 11.8, both x86_64 and aarch64.
> 
> `export LD_PRELOAD=/path/to/libjemalloc.so.2` still fixes it

I confirm this.  I have the same issue and fix with this solution.  I wonder if it is related to ruby install environment variable:

`RUBY_CONFIGURE_OPTS=--with-jemalloc rbenv install`
