### ISSUE TITLE
Filter not filtering

### ISSUE THREAD

**Issue by soundplusfury** [mastodon/mastodon#25762]
### Steps to reproduce the problem

I wanted to filter out any post with the words NSFW. So I created a filter for this. 

### Expected behaviour

It should filter these

### Actual behaviour

It does not or only does so in a limited way

### Detailed description

It only appears to do so in a limited way. I still see the content even though I have checked all the boxes not to. (I'm not sure what else to say here so I hope this is enough.) 

### Specifications

Firefox 113.0.2
Linux Mint 19 LTS.

**Comment by Trit34** [comment]
Same here: I have a filter set to hide the word “threads”, and it works well for Home and Mention columns, but not the Federated timeline…

![Capture d’écran_2023-07-07_01-27-43](https://github.com/mastodon/mastodon/assets/90716575/ceb98571-685f-439a-875c-d0fb64adc71d)

**Comment by ClearlyClaire** [comment]
What version of Mastodon are you using?

> Same here: I have a filter set to hide the words “threads” and “Elon”, and if it works well for Home and Mention columns, it’s not the case on the Federated timeline…

I assume the filters are also set to filter from the public timelines?
![image](https://github.com/mastodon/mastodon/assets/384364/d40fea20-06a0-4b47-a583-4dd6197f2b18)

**Comment by Trit34** [comment]
> What version of Mastodon are you using?
> 
> > Same here: I have a filter set to hide the words “threads” and “Elon”, and if it works well for Home and Mention columns, it’s not the case on the Federated timeline…
> 
> I assume the filters are also set to filter from the public timelines? ![image](https://user-images.githubusercontent.com/384364/251742309-d40fea20-06a0-4b47-a583-4dd6197f2b18.png)

The latest release (4.1.3 at that time, updated to 4.1.4 now). And yes, public timelines was enabled, too.

Since my last message, I cold see that sometimes, filters on public timelines work, sometimes not.

**Comment by Trit34** [comment]
I got it, I guess: when public timeline is refreshed (enable/disable “Media only” or reload the tab), filters work. But they won’t work on new posts until you refresh the column again.

**Comment by soundplusfury** [comment]
It doesn't do that on the desktop site. I can block or mute accounts but my filters don't always work, even the older ones. (Local timeline only, by the way.)

**Comment by ClearlyClaire** [comment]
Hm, this might be a regression in the streaming server, going to have a look. In addition, it looks like the “explore” page does not currently apply filters properly.

**Comment by regalialong** [comment]
I hate to bump issues, but this is critical for me as a minor since I don't want to view NSFW content.

**Comment by Trit34** [comment]
> I hate to bump issues, but this is critical for me as a minor since I don't want to view NSFW content.

It’s infortunate that not all NSFW content posters mark them as such, but have you enabled the hiding/blurring options in the settings?

**Comment by regalialong** [comment]
@Trit34 I have but that's off-topic mostly. I'd prefer to just not see it outright (since some profile contents like avatars can be NSFW as well), the functionality worked before.

I use a server that runs 4.1.4, posts streaming from Federated that should be filtered are still visible until I go on the poster's profile or I refresh.

**Comment by Taullo** [comment]
I think this and #25952 are related. It just seems like it's not grabbing the correct filters at all on the Explore page.

**Comment by ClearlyClaire** [comment]
> I think this and #25952 are related.

That's interesting, I will investigate further in that direction.

> It just seems like it's not grabbing the correct filters at all on the Explore page.

I will have a look, but I think those are different issues: the Explore tab did not apply any filter at all before #25887

**Comment by Taullo** [comment]
> > I think this and #25952 are related.
> 
> That's interesting, I will investigate further in that direction.
> 
> > It just seems like it's not grabbing the correct filters at all on the Explore page.
> 
> I will have a look, but I think those are different issues: the Explore tab did not apply any filter at all before #25887

Ooops sorry I misspoke. I meant Firehose, not Explore. It seems like it's an issue mainly when it's pulling down new posts. The correct filters are applied at page load but then when new posts are loaded in, it applies the wrong filters. This is on our fork of Glitch though and not vanilla Mastodon so I'm not sure if we're seeing different behavior.

**Comment by GrtFS** [comment]
I've had this issue since adding Filters ~8 months ago.  They don't work in #Explore.

My server (mstdn.social) is running 4.1.6.
I've just deleted a Filter.
Then made it again. 
Still #Cats in #Explore.

**Comment by ClearlyClaire** [comment]
Yeah, the explore part is not covered by 4.1.6.

**Comment by yllekz** [comment]
Filters haphazardly work for me. They seem to be sensitive to letter casing as well as tend to just not work for no explainable reason. The wildcard matching either is or is not present too which makes it frustrating to understand how it functions.

**Comment by ClearlyClaire** [comment]
@yllekz what version of Mastodon are you using, and what apps, if any? Filters should be case-insensitive, and there is no wildcard matching. Each keyword can be set as matching whole words only, or matching anywhere in words.

**Comment by thekingrat** [comment]
I'm seeing this on SFBA.social Local feed. It's running 4.1.4.  Doesn't filter as posts come in, but if I refresh they get filtered.

**Comment by Trit34** [comment]
> I'm seeing this on SFBA.social Local feed. It's running 4.1.4. Doesn't filter as posts come in, but if I refresh they get filtered.

Since it’s fixed in 4.1.6, you/your admin should update this instance ASAP.

**Comment by thekingrat** [comment]
> Since it’s fixed in 4.1.6, you/your admin should update this instance ASAP.

Is it?  All I see in this discussion is you asking if another person is using 4.1.6 and ClearlyClaire saying something was done for 4.1.6.  There's also someone else ([GrtFS](https://github.com/GrtFS)) saying whatever was done in 4.1.6 didn't fix filters.

I would appreciate some clarity, rather than trying to guess about oblique references.

**Comment by soundplusfury** [comment]
Does the 4.1.6 refer to an app? My original problem was with filters not working within a browser.

**Comment by ClearlyClaire** [comment]
> infosec.exchange. Not sure the version.

infosec.exchange seems to not have updated after the 4.1.6 fix was introduced!

**Comment by thekingrat** [comment]
> * 4.1.3 introduced a bug that makes the Federated and Local timelines sometimes apply the wrong filter; it has been fixed in 4.1.6

Thanks!

**Comment by ThisIsMissEm** [comment]
@ClearlyClaire I think we can close this issue now as fixed?

**Comment by ClearlyClaire** [comment]
I think so, yes.
