### ISSUE TITLE
4.1.5: 500 Error processing thumbnail for uploaded media with .mp4 and .gifs

### ISSUE THREAD

**Issue by neilzone** [mastodon/mastodon#26170]
### Steps to reproduce the problem

1. Log in to the web interface
2. Upload a .mp4 video or a .gif file
3. On screen error: "500 Error processing thumbnail for uploaded media"
...

### Expected behaviour

Video/file should have uploaded

### Actual behaviour

Error message

### Detailed description

Running `journalctl -fu mastodon-web`, I get:

```
Jul 25 19:33:35 nuc3 bundle[3851]: [29975bf9-ec83-4069-bb84-93619c240dc3] [paperclip] Trying to link /tmp/RackMultipart20230725-3851-3j86dh.mp4 to /tmp/78e6221f6393d1356681db398f14ce6d20230725-3851-jyblqr.mp4
Jul 25 19:33:35 nuc3 bundle[3851]: [29975bf9-ec83-4069-bb84-93619c240dc3] [paperclip] Trying to link /tmp/78e6221f6393d1356681db398f14ce6d20230725-3851-jyblqr.mp4 to /tmp/9a9126c0838f1ad405a5a922382bd6fe20230725-3851-og5e1a.mp4
Jul 25 19:33:35 nuc3 bundle[3851]: [29975bf9-ec83-4069-bb84-93619c240dc3] Command :: file -b --mime '/tmp/9a9126c0838f1ad405a5a922382bd6fe20230725-3851-og5e1a.mp4'
Jul 25 19:33:35 nuc3 bundle[3851]: [29975bf9-ec83-4069-bb84-93619c240dc3] method=POST path=/api/v2/media format=html controller=Api::V2::MediaController action=create status=500 duration=371.87 view=0.82 db=1.40
```

I'm afraid I'm not sure where to go next with this.

### Mastodon instance

mastodon.neilzone.co.uk

### Mastodon version

4.1.5

### Browser name and version

Firefox 115.0.2 (64-bit) (via flatpak)

### Operating system

Debian 12.1

**Comment by renchap** [comment]
Do you have `ffmpeg` installed on your system? Is it working correctly?

**Comment by neilzone** [comment]
> Do you have `ffmpeg` installed on your system? Is it working correctly?

I have it installed:

```
ffmpeg version 5.1.3-1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
```

I've just tested it, as the mastodon user, converting the .mp4 file I was trying to upload into a .gif, in the /tmp folder, and it worked so, yes, I think ffmpeg is working.

**Comment by rasos** [comment]
Same here since upgrade to 4.1.5 e.g. with this video https://faircloud.eu/nextcloud/index.php/s/k4fSmeSg6HoPiSe (reduced size with ffshare app to H264 1280x720) - also tried with non-pre-processed video.

**Comment by tyrosinase** [comment]
Also getting this with png files on mastohost, though I'd have to pester Hugo to get the journal entries.

**Comment by Stapper** [comment]
same setup, same issue. Any ideas?

**Comment by annatech** [comment]
I have been experiencing a similar issue with a containerized version of Mastodon, even now that I upgraded to 4.1.6. I've been hesitant to post that issue here until I can 100% its not due to configuration error, but so far, I have found nothing to indicate that is the case.

I deployed my cluster to AWS with Terraform Cloud and run it on ECS with Fargate and expose routes via CloudFront > AWS ALB.  I use S3 for media storage.

For any media I attempt to post which needs to be processed (animated gifs or mp4s), I get the error:
`422 Error processing thumbnail for uploaded media`

**Current behavior**

    User clicks on paperclip icon to attach an animated gif to a post
    The media item uploads and the post windows indicates that it is uploading and then processing
    After about 28.5 seconds, the upload stalls and throws the following error:
    -- "422 Error processing thumbnail for uploaded media"
    After that, the page needs to be reloaded before the attachment action can work again.
    
**Investigation**
I noticed that, during this event, Sidekiq reports the following retry action:

    Queue: default
    Job: PostProcessMediaWorker
    Arguments: %id_of_media%
    Error:
    (example)
    Errno::ENOENT: No such file or directory @ rb_sysopen - /opt/mastodon/public/system/media_attachments/files/110/888/339/885/320/433/original/e4b9cc41c743c791.mp4

The processed file appears as an mp4, successfully, with the correct S3 directory path.
Example:
/media_attachments/files/110/888/339/885/320/433/original/e4b9cc41c743c791.mp4 

So far, I have been unable to identify WHY Sidekiq fails with a reference to a **missing local file,** when the instance is otherwise correctly configured to store and serve media via S3 + CloudFront.

**Comment by ckinlund** [comment]
This still occurs (my server is running v4.2.0-rc2+glitch). In the case of one uploaded video I tried, it simply remained on “processing” for over 10 minutes and never allowed posting; doing the same steps with a third-party client (Ivory for iOS) failed after attempting the post. This was a 1280x960 mp4-encoded .mov container.

**Comment by neilzone** [comment]
I've fixed it for me: [here's how](https://neilzone.co.uk/2023/12/fixing-mastodon-error-processing-thumbnail-for-uploaded-media-video-uploading/).

I don't understand *why* I needed to change `ffmpeg` and `ffprobe`, but it now works.

**Comment by renchap** [comment]
Can you check which `ffmpeg` version was installed before you switched to the statically compiled one, and which one is now installed?

You can check the version using `ffmpeg -version`

**Comment by neilzone** [comment]
> Can you check which `ffmpeg` version was installed before you switched to the statically compiled one

Before (at least, at the time I first reported this):

```
ffmpeg version 5.1.3-1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
```
> and which one is now installed?

```
ffmpeg version 5.1.4-0+deb12u1 Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 12 (Debian 12.2.0-14)
```

(Someone mentioned that the stock Debian version of ffmpeg might lack codecs necessary for this, and that it might also work using the `deb-multimedia.org` version of ffmpeg.)

**Comment by rasos** [comment]
Video uploads and processing is still not working with `ffmpeg version 5.1.4-0+deb12u1` (which is shipped in the mastodon docker image 4.2.7). 

I think we should build a nightly version with the latest static builds from https://johnvansickle.com/ffmpeg/ as described here  https://neilzone.co.uk/2023/12/fixing-mastodon-error-processing-thumbnail-for-uploaded-media-video-uploading/ to do some further testing @Gargron

**Comment by rasos** [comment]
After upgrading to Mastodon 4.3.1, which comes with a freshly built ffmeg #30569, this is still an issue. In my case it seems that the video file is either cropped or assigned with a wrong MIME type. It gets the file from Minio S3. Changing the multipart threshold to 250MB fixed it for a Scaleway S3 bug as described in this issue https://github.com/mastodon/mastodon/issues/22335#issuecomment-1373533668 . But also a video with 4 MB fails with 422, which is below the default multipart threshold for S3. So just getting some chunked file due to an S3 problem should not be our case.  We just see in the logs:

> WARN: Paperclip::Error: Error while transcoding /tmp/d4f7402d7613e897041f7e84dadf881f20241027-1-n9ioyv.mp4: unsupported file     
> class=PostProcessMediaWorker jid=7b40bfa7e3e3d3c8a95d5f64 ERROR: Processing media attachment 113380878687495744 failed with Error while transcoding /tmp/d4f7402d7613e897041f7e84dadf881f20241027-1-n9ioyv.mp4: unsupported file

Related to https://github.com/mastodon/mastodon/issues/32640

**Comment by rasos** [comment]
I could solve my problem with video files processing by adding the S3 env 

`S3_FORCE_SINGLE_REQUEST: "true"`

This was introduced a while ago as the ruby storage library paperclip is a bit outdated and some S3 providers seem not to be fully compatible  https://github.com/mastodon/mastodon/issues/16822#issuecomment-2559634163 .
