### ISSUE TITLE
opening multiple windows or tabs implements DDOS attack causing user interface to fail with Rate limited error

### ISSUE THREAD

**Issue by alreadyinuse** [mastodon/mastodon#27282]
### Steps to reproduce the problem

1. open multiple windows or tabs with URLs of various user posts, DMs, etc of user's mastodon host server
2.
3.
...

### Expected behaviour

not implement DDOS attack

### Actual behaviour

implemented DDOS attack

### Detailed description

opening multiple windows or tabs implements DDOS attack causing user interface to fail with Rate limited error in each of the windows/tabs, making mastodon unusable for that user.  See attached animated gif. 

workaround is to use a 3rd party plugin to force the various tabs to stop their DDOS attack

if project is unable to implement user interface that does not have this DDOS problem, then probably having concurrent connections open from multiple windows/tabs should somehow be disabled.  If unable to implement that, probably should disclose this problem in the documentation.  Should probably also provide a link directly to the documentation from somewhere in the user interface.  As in, PTFM (provide the friendly manual).

![mastodon DDOS](https://github.com/mastodon/mastodon/assets/65797538/5c34da60-6075-4b14-a18e-1eea13f5334c)

### Mastodon instance

kolektiva.social

### Mastodon version

v4.2.0.  (FYI this form is incorrect, this is not displayed at the bottom of the About page)

### Browser name and version

firefox 118.0

### Operating system

Windows 10 Pro version 22H2

**Comment by andypiper** [comment]
Assigning to myself to check on the issue the user has raised in the issue template.

**Comment by ClearlyClaire** [comment]
There are two issues in this report:
1. opening multiple tabs may cause you to run into rate limits
2. under certain conditions, running into an error (including rate limits) will cause requests to be re-issued in an infinite loop

That second issue is partly addressed by https://github.com/mastodon/mastodon/pull/27286 (but there may be other cases of this).

**Comment by norpol** [comment]
Related issue comment here https://github.com/mastodon/mastodon/issues/25644#issuecomment-1703108503 that suggests utilizing the "page visibility api" (as someone on Discord also pointed that out).

The behavior still showed up for me after having 13 different mastodon.social tabs open.

**Comment by ke352802081770314** [comment]
Just saw this issue, I am also annoyed by this, already happens with 4 or 5 open tabs to me, always towards the end of a 5 minute slice (e.g. at 15:39 it will display "please retry after 15:40"). My instance runs v4.3.1

**Comment by Aligorith** [comment]
Is there likely to be any timeline for getting this issue resolved?

While it is a bit of a pain on a desktop browser, on something like Firefox Android, there have been numerous times over the past year or so where my phone battery has been quickly drained by this bug.


Some suggestions for what can be done here (Caveat: I'm unfamiliar with the internals here, so this may not really be what's happening, or what can be done):
1) When the notification counter reaches "40+" (or the "Load More/Newer" type things), the background worker threads that do that updating should just be turned off / paused until the user manually refreshes or interacts with the page - preferably via an explicit "Fetch Updates" button.
   
   That's because in practice, those elements can no longer show any new updates, but their frequent polling past this point just messes with whatever other tabs may be open.

2) Even Better: Stop these background workers as soon as the tab loses focus, and only restart them when the tab regains focus

3) Optionally: Provide a settings option to disable this background polling/updating functionality completely
