### ISSUE TITLE
Switch from inline audio player to pop-up player resets volume adjustment

### ISSUE THREAD

**Issue by 4censord** [mastodon/mastodon#27958]
### Steps to reproduce the problem

1. Listen to any audio attachment
2. Adjust the volume
3. Scroll the original message of the screen
5. The audio gets put into a floating overlay
6. The volume adjustment returns to default (100%), blasting my ears

### Expected behaviour

The volume addjustment should be keept

### Actual behaviour

The volume adjustment resets to the default volume, 100%

### Detailed description

When switching from the inline audio player to the floating audio player, the volume adjustment is not kept

### Mastodon instance

unfug.social

### Mastodon version

v4.1.3

### Browser name and version

Mozilla Firefox 119.0.1

### Operating system

Linux (Linux thearch 6.6.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 08 Nov 2023 16:05:38 +0000 x86_64 GNU/Linux)

**Comment by vmstan** [comment]
This is fixed by #27488 which will be available in a future released version.

**Comment by 4censord** [comment]
Amazing, thanks.
Should this issue be closed now, or once this is released?

**Comment by vmstan** [comment]
It can be closed.

**Comment by 4censord** [comment]
This seems to still be happening on Mastodon v4.2.5.
The post in question is text and audio post from a `Sharkey 2023.12.0` instance.

There have been minor version releases in the meantime, has this just not been included yet?

**Comment by 4censord** [comment]
This is still happening as of `Mastodon v4.2.9`.
This time a text and audio post originating from a `Glitch v4.3.0-alpha.4+glitch` instance.

**Comment by vmstan** [comment]
The fix will be available as part of Mastodon 4.3.
