### ISSUE TITLE
Accessibility issue with privacy/content warning controls in the tootbox

### ISSUE THREAD

**Issue by moggers87** [mastodon/mastodon#6028]
(This was originally a comment on #5824)

The privacy/content-warning buttons are not properly accessible - they can be selected via keyboard, but they don't offer much visual feedback. Compare with the emoji and "Toot" buttons:

1. Emoji selected:
![Emoji selected](https://user-images.githubusercontent.com/1490673/33609741-2ec8a7f0-d9c1-11e7-9609-a101a3699981.png)

2. "Toot" selected:
![Toot selected](https://user-images.githubusercontent.com/1490673/33609742-2eead2e4-d9c1-11e7-988f-34ef454c5aba.png)

3. Privacy button selected (note the limited contrast between the buttons)
![privacy button selected](https://user-images.githubusercontent.com/1490673/33609744-2f0dd6b8-d9c1-11e7-80c0-7047ce44954f.png)

For those of you unfamiliar with keyboard control in browsers: click the textbox and hit tab a bunch of times, you'll first see the emoji button selected (if you press space or enter, you'll get the emoji picker pop up). If you hit tab a few more times you'll see the "Toot" button is selected - hitting space or enter here will post your toot.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by moggers87** [comment]
These W3C document on [colour contrast](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html) and on [indicating keyboard focus](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-visible.html) might be worth a read too

**Comment by Xkeeper0** [comment]
If you have some form of User CSS available, you can make them more usable by using the following CSS. This will also add a background showing the available clicking area to the buttons as well.

Focusing a button and then its active state:
![image](https://user-images.githubusercontent.com/1077535/34888020-67af9bbc-f77d-11e7-9adf-8f16eccbc890.png) ![image](https://user-images.githubusercontent.com/1077535/34888025-6b3729a8-f77d-11e7-9011-26b6ea7c41a6.png)

Toggled "CW" button:
![image](https://user-images.githubusercontent.com/1077535/34888037-77bba3de-f77d-11e7-82e5-6adcf3f47492.png)


For posterity, the default look without this CSS:
![image](https://user-images.githubusercontent.com/1077535/34888099-b9390c2a-f77d-11e7-8ca4-4d307ef0b904.png)


```css
.compose-form__buttons button {
    /* make the new toot buttons stand out too */
	background: rgba(0, 0, 0, .2);
	border-radius: .3em;
	color: #fff;
	margin-right: .5em;
}

.compose-form__buttons button.active {
	/* make the cw button more obvious when toggled */
	background: rgba(0, 0, 0, .6);
	color: #ff4;
	box-shadow: inset 0px 2px 3px 1px rgba(0, 0, 0, .6);
}
	
.compose-form__buttons button:hover, .compose-form__buttons button:focus {
	/* make all the buttons stand out when you hover over them */
	background: rgba(0, 0, 0, .4);
	color: #fff;
}
```

**Comment by moggers87** [comment]
Just a quick update: this issue now includes the "Toot" button as it has lost the dashed outline it had previously.

**Comment by moggers87** [comment]
This is still an issue.

**Comment by moggers87** [comment]
Actually, that might not be true: I'm on two instances, one is running Mastodon V2.9.3 and the other is running Glitchsoc v3.0.1+glitch. The one running Glitchsoc appears to have solved this issue but I don't know it that's a Glitchsoc change or something that was fixed in V3.0.x

**Comment by Xkeeper0** [comment]
Left: Attach selected via keyboard. Right: None (though CW is enabled.)

![2019-10-29-11:06:24-Selection](https://user-images.githubusercontent.com/1077535/67795908-4985d480-fa3c-11e9-9f29-89c2244b6469.png) ![2019-10-29-11:06:41-Selection](https://user-images.githubusercontent.com/1077535/67795912-4be82e80-fa3c-11e9-9310-4fe71bd01c58.png)

It is not quite as egregious as before, but still not great. However, adding a poll reveals that the old problem never quite went away. (Note that in this, the appearance doesn't change regardless of which one is selected, even though "Add a choice" looks as if it might be focused)

![2019-10-29-11:07:14-Selection](https://user-images.githubusercontent.com/1077535/67795974-6c17ed80-fa3c-11e9-8944-9fd131b962f7.png)

Both the "Add a choice" and "1 day" options do not have any visual indication of being selected. The "1 day" field also appears to be disabled, and uses a "spinner" (↕) instead of a dropdown (▼). Spinners are typically for incremental numerical values and not fixed-value dropdowns. The radio buttons are also selectable, despite being non-functional/for show.

**Comment by trwnh** [comment]
Closing as stale since the compose form has been redesigned. Please file a new issue if there are any accessibility concerns with the new design
